-- Lumi Labs / AI Creator Hub
-- Supabase setup for Auth + subscribers + project following.
-- Run this file once in Supabase SQL Editor.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text unique not null,
  name text,
  avatar_url text,
  provider text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.subscribers (
  id bigint generated by default as identity primary key,
  email text unique not null,
  user_id uuid references auth.users(id) on delete set null,
  name text,
  avatar_url text,
  source text not null default 'follow_form',
  provider text not null default 'email',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.followed_projects (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  project_slug text not null,
  created_at timestamptz not null default now(),
  unique (user_id, project_slug)
);

create table if not exists public.memberships (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  plan text not null default 'free',
  status text not null default 'active',
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id)
);

alter table public.profiles enable row level security;
alter table public.subscribers enable row level security;
alter table public.followed_projects enable row level security;
alter table public.memberships enable row level security;

drop policy if exists "Users can read own profile" on public.profiles;
create policy "Users can read own profile"
on public.profiles
for select
to authenticated
using (auth.uid() = id);

drop policy if exists "Users can update own profile" on public.profiles;
create policy "Users can update own profile"
on public.profiles
for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists "Users can insert own profile" on public.profiles;
create policy "Users can insert own profile"
on public.profiles
for insert
to authenticated
with check (auth.uid() = id);

drop policy if exists "Users can read own subscriber record" on public.subscribers;
create policy "Users can read own subscriber record"
on public.subscribers
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can insert own subscriber record" on public.subscribers;
create policy "Users can insert own subscriber record"
on public.subscribers
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can update own subscriber record" on public.subscribers;
create policy "Users can update own subscriber record"
on public.subscribers
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users can read followed projects" on public.followed_projects;
create policy "Users can read followed projects"
on public.followed_projects
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can follow projects" on public.followed_projects;
create policy "Users can follow projects"
on public.followed_projects
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can update followed projects" on public.followed_projects;
create policy "Users can update followed projects"
on public.followed_projects
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users can read own membership" on public.memberships;
create policy "Users can read own membership"
on public.memberships
for select
to authenticated
using (auth.uid() = user_id);

create index if not exists subscribers_email_idx on public.subscribers (email);
create index if not exists followed_projects_user_id_idx on public.followed_projects (user_id);
create index if not exists memberships_user_id_idx on public.memberships (user_id);
