-- Lumi Labs / AI Creator Hub
-- Supabase setup for Auth + subscribers + project following.
-- Run this file once in Supabase SQL Editor.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text unique not null,
  name text,
  avatar_url text,
  provider text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.subscribers (
  id bigint generated by default as identity primary key,
  email text unique not null,
  user_id uuid references auth.users(id) on delete set null,
  name text,
  avatar_url text,
  source text not null default 'follow_form',
  provider text not null default 'email',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.followed_projects (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  project_slug text not null,
  created_at timestamptz not null default now(),
  unique (user_id, project_slug)
);

create table if not exists public.memberships (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  plan text not null default 'free',
  status text not null default 'active',
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id)
);

create table if not exists public.ai_usage_limits (
  id bigint generated by default as identity primary key,
  bucket_key text not null,
  client_ip text not null,
  action text not null,
  window_start timestamptz not null default date_trunc('day', now()),
  count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (bucket_key, window_start)
);

create table if not exists public.project_feedback (
  id bigint generated by default as identity primary key,
  project text not null,
  rating text not null check (rating in ('good', 'okay', 'bad')),
  comment text,
  page_path text,
  user_email text,
  user_name text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.pilot_requests (
  id uuid primary key default gen_random_uuid(),
  name text,
  company text,
  role text,
  file_type text not null,
  monthly_volume text,
  contact text not null,
  note text,
  source text default 'business_pilot',
  page_path text,
  created_at timestamptz not null default now()
);

create or replace function public.consume_ai_usage(
  p_bucket_key text,
  p_client_ip text,
  p_action text,
  p_max integer default 5
)
returns table (
  allowed boolean,
  used integer,
  remaining integer,
  reset_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_window_start timestamptz := date_trunc('day', now());
  v_reset_at timestamptz := date_trunc('day', now()) + interval '1 day';
  v_used integer;
begin
  insert into public.ai_usage_limits (bucket_key, client_ip, action, window_start, count)
  values (p_bucket_key, p_client_ip, p_action, v_window_start, 1)
  on conflict (bucket_key, window_start)
  do update set
    count = public.ai_usage_limits.count + 1,
    updated_at = now()
  where public.ai_usage_limits.count < p_max
  returning count into v_used;

  if v_used is null then
    select count into v_used
    from public.ai_usage_limits
    where bucket_key = p_bucket_key
      and window_start = v_window_start;

    return query select false, coalesce(v_used, p_max), 0, v_reset_at;
    return;
  end if;

  return query select true, v_used, greatest(p_max - v_used, 0), v_reset_at;
end;
$$;

alter table public.profiles enable row level security;
alter table public.subscribers enable row level security;
alter table public.followed_projects enable row level security;
alter table public.memberships enable row level security;
alter table public.ai_usage_limits enable row level security;
alter table public.project_feedback enable row level security;
alter table public.pilot_requests enable row level security;

drop policy if exists "Users can read own profile" on public.profiles;
create policy "Users can read own profile"
on public.profiles
for select
to authenticated
using (auth.uid() = id);

drop policy if exists "Users can update own profile" on public.profiles;
create policy "Users can update own profile"
on public.profiles
for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists "Users can insert own profile" on public.profiles;
create policy "Users can insert own profile"
on public.profiles
for insert
to authenticated
with check (auth.uid() = id);

drop policy if exists "Users can read own subscriber record" on public.subscribers;
create policy "Users can read own subscriber record"
on public.subscribers
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can insert own subscriber record" on public.subscribers;
create policy "Users can insert own subscriber record"
on public.subscribers
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can update own subscriber record" on public.subscribers;
create policy "Users can update own subscriber record"
on public.subscribers
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users can read followed projects" on public.followed_projects;
create policy "Users can read followed projects"
on public.followed_projects
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can follow projects" on public.followed_projects;
create policy "Users can follow projects"
on public.followed_projects
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can update followed projects" on public.followed_projects;
create policy "Users can update followed projects"
on public.followed_projects
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users can read own membership" on public.memberships;
create policy "Users can read own membership"
on public.memberships
for select
to authenticated
using (auth.uid() = user_id);

create index if not exists subscribers_email_idx on public.subscribers (email);
create index if not exists followed_projects_user_id_idx on public.followed_projects (user_id);
create index if not exists memberships_user_id_idx on public.memberships (user_id);
create index if not exists ai_usage_limits_bucket_idx on public.ai_usage_limits (bucket_key, window_start);
create index if not exists project_feedback_project_idx on public.project_feedback (project, created_at desc);
create index if not exists project_feedback_rating_idx on public.project_feedback (rating, created_at desc);
create index if not exists pilot_requests_created_idx on public.pilot_requests (created_at desc);
create index if not exists pilot_requests_contact_idx on public.pilot_requests (contact);
